insert into teams (team_name) values ('Ring-tailed gecko');
insert into teams (team_name) values ('Black-tailed prairie dog');
insert into teams (team_name) values ('Coke''s hartebeest');

insert into employees (full_name, email, phone_number, date_of_birth, monthly_salary, employee_team_id) values ('Mella Grabiec', 'mgrabiec0@redcross.org', '871-842-0468', '1997-05-18', 925.99, 1);
insert into employees (full_name, email, phone_number, date_of_birth, monthly_salary, employee_team_id) values ('Waverley Linger', 'wlinger1@studiopress.com', '378-170-0149', '2003-12-11', 508.08, 2);
insert into employees (full_name, email, phone_number, date_of_birth, monthly_salary, employee_team_id) values ('Essie Perillio', 'eperillio2@samsung.com', '924-864-5653', '1967-12-23', 2428.39, 3);
insert into employees (full_name, email, phone_number, date_of_birth, monthly_salary, employee_team_id) values ('Shellie Jaggers', 'sjaggers3@nyu.edu', '618-867-6049', '2002-08-12', 2633.45, 1);
insert into employees (full_name, email, phone_number, date_of_birth, monthly_salary, employee_team_id) values ('Wenda Caston', 'wcaston4@friendfeed.com', '178-362-9037', '1975-04-20', 2131.03, 2);
insert into employees (full_name, email, phone_number, date_of_birth, monthly_salary, employee_team_id) values ('Matthias Grave', 'mgrave5@imgur.com', '824-500-0248', '1965-12-18', 1369.97, 3);
insert into employees (full_name, email, phone_number, date_of_birth, monthly_salary, employee_team_id) values ('Janetta Workman', 'jworkman6@imdb.com', '619-849-8175', '1973-01-26', 2323.49, 1);
insert into employees (full_name, email, phone_number, date_of_birth, monthly_salary, employee_team_id) values ('York Raspel', 'yraspel7@accuweather.com', '183-854-3710', '1996-06-07', 2549.75, 2);
insert into employees (full_name, email, phone_number, date_of_birth, monthly_salary, employee_team_id) values ('Brnaba Lucian', 'blucian8@blogs.com', '754-697-2767', '1990-01-10', 2842.3, 3);
insert into employees (full_name, email, phone_number, date_of_birth, monthly_salary, employee_team_id) values ('Mella Saltmarsh', 'msaltmarsh9@army.mil', '226-485-6726', '1999-10-25', 1895.22, 1);

insert into tasks (title, description, due_date, assignee) values ('sem', 'ultrices mattis odio donec vitae nisi nam ultrices libero non mattis', '2022-12-14 00:43:06', 6);
insert into tasks (title, description, due_date, assignee) values ('fermentum', 'quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis', '2022-04-23 04:21:08', 5);
insert into tasks (title, description, due_date, assignee) values ('ipsum dolor', 'erat fermentum justo nec condimentum neque sapien placerat ante nulla', '2023-04-01 16:22:11', 1);
insert into tasks (title, description, due_date, assignee) values ('vivamus', 'nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', '2023-11-03 02:05:08', 6);
insert into tasks (title, description, due_date, assignee) values ('in', 'a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum', '2022-04-05 01:43:08', 4);
insert into tasks (title, description, due_date, assignee) values ('in', 'fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend', '2022-08-16 04:00:21', 2);
insert into tasks (title, description, due_date, assignee) values ('venenatis non', 'ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam', '2022-12-15 01:14:02', 3);
insert into tasks (title, description, due_date, assignee) values ('augue', 'felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus', '2024-02-27 09:01:58', 5);
insert into tasks (title, description, due_date, assignee) values ('justo maecenas', 'ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer', '2022-10-31 15:30:41', 3);
insert into tasks (title, description, due_date, assignee) values ('justo', 'ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor', '2023-07-16 22:34:14', 2);
insert into tasks (title, description, due_date, assignee) values ('sed', 'pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi', '2024-01-10 05:48:22', 4);
insert into tasks (title, description, due_date, assignee) values ('velit eu', 'lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat', '2022-08-20 04:17:53', 10);
insert into tasks (title, description, due_date, assignee) values ('dictumst etiam', 'tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed', '2023-03-20 18:56:10', 1);
insert into tasks (title, description, due_date, assignee) values ('mi', 'in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis', '2022-09-28 18:57:55', 7);
insert into tasks (title, description, due_date, assignee) values ('pede', 'nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie', '2022-10-25 05:00:25', 8);
insert into tasks (title, description, due_date, assignee) values ('nullam sit', 'et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam', '2023-11-15 13:20:58', 8);
insert into tasks (title, description, due_date, assignee) values ('semper est', 'accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas', '2023-06-01 06:34:58', 8);
insert into tasks (title, description, due_date, assignee) values ('ornare consequat', 'platea dictumst etiam faucibus cursus urna ut tellus nulla ut', '2023-07-25 16:01:07', 6);
insert into tasks (title, description, due_date, assignee) values ('amet sapien', 'dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat', '2023-02-10 06:36:21', 3);
insert into tasks (title, description, due_date, assignee) values ('id', 'ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit', '2022-05-27 07:00:14', 8);
insert into tasks (title, description, due_date, assignee) values ('in faucibus', 'justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus', '2022-10-24 23:53:08', 4);
insert into tasks (title, description, due_date, assignee) values ('nulla', 'proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus', '2023-12-17 10:57:39', 10);
insert into tasks (title, description, due_date, assignee) values ('morbi sem', 'a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas', '2023-09-21 07:18:07', 2);
insert into tasks (title, description, due_date, assignee) values ('in faucibus', 'purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor', '2023-10-02 17:44:41', 9);
insert into tasks (title, description, due_date, assignee) values ('elit proin', 'semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam', '2023-01-15 15:45:39', 5);
insert into tasks (title, description, due_date, assignee) values ('dis', 'ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu', '2023-10-28 04:40:57', 9);
insert into tasks (title, description, due_date, assignee) values ('vulputate', 'cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit', '2023-01-10 18:57:27', 5);
insert into tasks (title, description, due_date, assignee) values ('nulla suspendisse', 'egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis', '2023-07-28 20:05:33', 6);
insert into tasks (title, description, due_date, assignee) values ('ullamcorper purus', 'quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non', '2023-07-03 15:46:15', 8);
insert into tasks (title, description, due_date, assignee) values ('risus', 'rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis', '2024-01-23 14:39:10', 10);